# Generated by Django 5.2 on 2025-04-12 22:37

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_departement', models.CharField(max_length=120, unique=True)),
                ('departement_code', models.CharField(max_length=30, unique=True)),
                ('decription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=30)),
                ('home_address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Aadis', 'Addis'), ('Jima', 'Jima'), ('Hawsa', 'Hawasa')], max_length=160)),
                ('nationality', django_countries.fields.CountryField(max_length=150)),
                ('postal_code', models.CharField(max_length=20)),
                ('employe_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('job_title', models.CharField(max_length=40)),
                ('employement_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], max_length=23)),
                ('superviser', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ManyToManyField(blank=True, to='api.departement')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='departement_head',
            field=models.OneToOneField(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_departement', to='api.employementdetails'),
        ),
    ]
