# Generated by Django 5.2 on 2025-04-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_departement_employementdetails_departements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='departement',
            name='departement_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_departement', to='api.employementdetails'),
        ),
        migrations.AlterField(
            model_name='employementdetails',
            name='employe_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
