# Generated by Django 5.2 on 2025-04-13 11:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_decription_departement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employementdetails',
            name='employe_id',
            field=models.CharField(default=api.models.unique_id, editable=False, max_length=30, unique=True),
        ),
    ]
