# Generated by Django 5.2 on 2025-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employementdetails_employe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employementdetails',
            name='employement_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'contract'), ('Fx', 'Filexble')], max_length=23),
        ),
        migrations.AlterField(
            model_name='employementdetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10),
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_skill', models.CharField(max_length=36)),
                ('descriptions', models.TextField()),
                ('lobation_0f_skill_get', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=45)),
                ('dept', models.ManyToManyField(max_length=30, to='api.departement')),
            ],
        ),
    ]
