# Generated by Django 5.2 on 2025-04-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employementdetails_employement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficions', models.CharField(choices=[('Advanced', 'advanced'), ('middle_level', 'middle_level'), ('Beginer', 'Beginer')], max_length=200)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employementdetails')),
                ('skill_optaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skills')),
            ],
        ),
    ]
